name: Deploy to Localhost via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH into local server and restart services
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH connection
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          port: 22
          script: |
            cd C:/Users/${{ secrets.SSH_USERNAME }}/IdeaProjects/hello-fullstack
            docker-compose down
            docker-compose up -d --build
